import { Inter } from "next/font/google";
import "./globals.css";
import { SoundProvider } from "@/contexts/SoundContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SoundProvider>
        <body className={inter.className}>{children}</body>
      </SoundProvider>
    </html>
  );
}
